### ISSUE TITLE
how to use with electron?

### ISSUE THREAD

**Issue by flytam** [davetimmins/esri-loader-react#1]
My project wants to use react+electron+webpack, but when i run the project,it has error that 'path must be a string', I think it has some conflict between  node's require and AMD's require.  Can it successfully in electron?

**Comment by tomwayson** [comment]
See https://github.com/tomwayson/esri-loader/issues/21#issuecomment-296677868

**Comment by flytam** [comment]
I have tried the solution mentioned on the website you give.But it seems to have no effect.

**Comment by davetimmins** [comment]
Gonna close this as the issue can be tracked in the esri-loader repo as mentioned above.
