### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by CraigglesO** [davetimmins/esri-loader-react#3]
I posted in esri-loader as well, but I was wondering if I put in:
```
const mapOptions = {
    url: 'https://js.arcgis.com/4.5/',
    has: { "esri-featurelayer-webgl": 1 }
};
```

Will this work for webgl support? ^_^
Thanks for you work..

**Comment by davetimmins** [comment]
No, the options that get passed down to esri-loader are just the ones used by esri-loader, so only really the url. For that webgl setting you can just include the dojoConfig script anywhere in your app before you mount / load the esri JS API, so for example in your index page 

```
<body>
  <div id="demo">      
  </div>
  <script>
    var dojoConfig = {
      has: {
        "esri-featurelayer-webgl": 1
      }
    };
  </script>
</body>
```
