### ISSUE TITLE
esri-loader-react question

### ISSUE THREAD

**Issue by guzhongren** [davetimmins/esri-loader-react#4]
in my [components](https://github.com/guzhongren/YanqiProject/blob/master/src/components/baseComponets/esriMap/index.tsx) of  my project ,
i lmport EsriLoader from 'esri-loader-react'; and import { dojoRequire } from 'esri-loader'； but the app is console this
![image](https://user-images.githubusercontent.com/8743692/32229261-5d5808be-be8b-11e7-8c22-53c7028ba4a3.png)

please give me some suggestion... thank you

**Comment by davetimmins** [comment]
There's a couple of things to try. Remove the 

```
import EsriMap = require("esri/Map");
import MapView = require("esri/views/MapView");
```

statements as that way of importing doesn't work unless you want to load the Esri JS API as a normal script tag and then exclude it using the externals config in your webpack script. If that doesn't resolve the issue then it could also be the url used for the options as it looks like you're using a local build of the API and you may want to try using an absolute url nstead of a relative one.

**Comment by guzhongren** [comment]
hi!
1. use  your first method,  i write like this, and use
```
import EsriMap = require("esri/Map");
import MapView = require("esri/views/MapView");
```
![image](https://user-images.githubusercontent.com/8743692/32256404-ce72f546-bee9-11e7-98ef-c1f4d15d6f45.png)
but  the console display "dojo.require not a function";
2. use your second, i change my api url, and use your example and my local url,
![image](https://user-images.githubusercontent.com/8743692/32257217-bbd126c4-beee-11e7-8c91-10f7e79248be.png)

 the console has not change, the result is like previose issuse,
In my opinion， i need to use your second method to adapt to the new version  AGS API，need to your help,  thank you very much...

**Comment by davetimmins** [comment]
The first method is either remove those import statements OR use the externals. If you're using the externals then you don't need this library at all, they shouldn't be used together

**Comment by guzhongren** [comment]
oh yeee, i have seen your[ article](https://davetimmins.github.io/2017/07/19/esri-loader-react/)  and  resolved my question , the question is create map  should be in   componentDidMount of react lifecycle, thank you
