### ISSUE TITLE
React and Redux with esri-loader-react

### ISSUE THREAD

**Issue by forgo** [davetimmins/esri-loader-react#5]
I have an ArcGISMapContainer (redux container) and ArcGIS (react component).  In my map component's `render()` I call `<EsriLoaderReact options={options} onReady={...} />`

Mostly it's working great, but I need to calculate a bounding box to be stored in my redux state and update on the `view.on('drag', event => { ... })` of my MapView.

Unfortunately, my current implementation results in a bunch of these messages popping up in my console:

`warning.js?1792:33 Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effect`

This message goes away when I remove the redux action (attached to a prop from my map container) from within the `view.on('drag', event => { ... })` which itself is in the `onReady` function of `<EsriLoaderReact onReady={ ... } >`

Is there a better way of going about storing this derived bounding box in redux to maintain React paradigms?

**Comment by davetimmins** [comment]
Sounds like it is something to do with the prop triggering a re-render which is then interfering with the on listener but I'd have to see more to give you more details. You may also want to watch the `MapView.stationary` property using https://developers.arcgis.com/javascript/latest/api-reference/esri-core-watchUtils.html#whenTrue and then get the bounding box using the `viewpoint.extent`

**Comment by forgo** [comment]
@davetimmins I need to rephrase my question I think, to reduce the problem to the fundamental issue:

How can I create an `<EsriLoaderReact/>` component and then redraw only a part of it when one of my react component props changes?

Right now, I seem to have no control over redrawing parts of the map based on props coming into the component.

What I think *needs* to happen is I need to take the drawing part out of my `view.on('drag'` event, and only update my redux state with the bounds calculated there.

Then the rectangle is drawn on the map after the fact due to props changing. This method should avoid the infinite loops and race conditions I seemed to have been creating.... but how do I do that?

It seems like `<EsriLoaderReact>` needs to know everything you want to do upfront, with nothing dynamic. In other words, if I use the `bounds` in Redux (which should update with every drag event), I need some place to plug in the drawing logic to update the map outside of the drag event.

If I place it in the "onReady" (outside of the drag event), it never draws anything.

Should there be an "onChange" prop or something that captures new drawings based on React props passed in?

I'm a little confused how to do this. Thanks for your help on this one.

**Comment by davetimmins** [comment]
OK, I think I understand what you're asking a bit better now. 

All this component really does is wrap the calls to load and define / require the dojo modules used for the Esri JS API. It isn't a binding on the functionality that the Esri JS API exposes which means that if you want to have JS code to interact / update a map control then you would still do that outside of anything React specific.

If that is what you're after you may want to check out https://github.com/nicksenger/react-arcgis

**Comment by davetimmins** [comment]
Closing as I'm assuming you've gotten around your issue.

**Comment by hazrul** [comment]
@forgo did you manage to get around the issue? can you share the solution
